name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  # Increase memory for Node.js
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  build:
    name: Nx CI Job
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      
        # Step 3: Setup Bun
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      
      # Step 4: Install Biome
      - name: Install Biome
        run: bun install @biomejs/biome

      # Step 5: Lint Check
      - name: Lint Check
        run: bun run lint:check
      
      # Step 6: Format Check
      - name: Format Check
        run: bun run format:check

      # Step 7: Test
      - name: Test
        run: bun run test

  docker-build:
      name: Docker Build Verification
      runs-on: ubuntu-latest
      steps:
        # Step 1: Set up Docker Compose
        - name: Set up Docker
          uses: docker/setup-buildx-action@v3
        
        # Step 2: Verify Helios Service
        - name: Verify Helios Service
          run: |
            docker ps | grep helios || exit 1
            curl -sf http://localhost:8545/ || exit 1